default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test: &test
  <<: *default
  database: pagolatam_db_test<%= ENV['TEST_ENV_NUMBER'] %>

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>